(function(root) {
  const gamma = 1.4, number = '(\\d+(?:\\.\\d+)?)';
  const pressurePattern = new RegExp(`${number}\\s*(mpa|kpa|pa)\\b`, 'gi');
  const volumePattern = new RegExp(`${number}\\s*(m\\^?3|m³|cm\\^?3|cm³|(?:cubic\\s*)?(?:meters?|metres?)\\s*(?:cube|cubed)|l|liters?|litres?)`, 'gi');
  const toKPa = (n,u) => u.toLowerCase()==='mpa'?n*1000:u.toLowerCase()==='pa'?n/1000:n;
  const toM3 = (n,u) => { const x=u.toLowerCase().replace(/\s+/g,''); return x==='l'||x.startsWith('liter')||x.startsWith('litre')?n/1000:x.startsWith('cm')?n/1000000:n; };
  const extract = (text,pattern,convert) => [...text.matchAll(pattern)].map(m=>convert(Number(m[1]),m[2]));
  function solveAdiabaticQuestion(question) {
    const text=String(question||'').toLowerCase();
    if(!/adiabatic|no heat (?:transfer|exchange)|adiabat/.test(text)) return {error:'This focused lab accepts only adiabatic air piston-cylinder questions.'};
    const pressures=extract(text,pressurePattern,toKPa),volumes=extract(text,volumePattern,toM3);
    const asksWork=/work|work done|work output|work input/.test(text), asksPressure=/(?:final|ending)\s+pressure|find\s+(?:the\s+)?(?:final\s+)?pressure|\bp2\b/.test(text), asksVolume=/(?:final|ending)\s+volume|find\s+(?:the\s+)?(?:final\s+)?volume|find\s+v2|\bv2\b/.test(text);
    if(!(pressures[0]>0&&volumes[0]>0)) return {error:'Please include an initial pressure and initial volume with units.'};
    const p1=pressures[0],v1=volumes[0]; let p2=pressures[1]||null,v2=volumes[1]||null;
    if(!v2&&p2) v2=v1*(p1/p2)**(1/gamma); if(!p2&&v2) p2=p1*(v1/v2)**gamma;
    if(!(p2>0&&v2>0)) return {error:'Please include either a final pressure or a final volume so the other final-state value can be derived.'};
    const explicitVolumeTarget=/find\s+(?:the\s+)?(?:final\s+)?(?:volume|v2)\b/.test(text),explicitPressureTarget=/find\s+(?:the\s+)?(?:final\s+)?(?:pressure|p2)\b/.test(text);
    const workKJ=(p2*v2-p1*v1)/(1-gamma); return {p1,v1,p2,v2,workKJ,target:asksWork?'work':explicitVolumeTarget?'volume':explicitPressureTarget?'pressure':asksPressure?'pressure':asksVolume?'volume':'pressure'};
  }
  if(typeof module!=='undefined'&&module.exports)module.exports={solveAdiabaticQuestion}; if(typeof document==='undefined')return;
  const $=id=>document.getElementById(id),q=$('questionInput'),message=$('message'),lesson=$('lesson'),progress=$('progress');let state=null,animation=null;const f=(n,d=2)=>Number(n).toFixed(d);
  const canvas=(node,h)=>{const w=Math.max(260,Math.round(node.getBoundingClientRect().width)),d=Math.min(devicePixelRatio||1,2);node.width=w*d;node.height=h*d;const c=node.getContext('2d');c.scale(d,d);return{c,w,h}};
  function piston(t){const{c,w,h}=canvas($('pistonCanvas'),390),y=92+t*145,fall=state.p2<state.p1;c.fillStyle='#fbf7ff';c.fillRect(0,0,w,h);c.fillStyle='rgba(111,80,188,.5)';c.fillRect(w*.24,y+16,w*.52,h-y-68);c.strokeStyle='#6b46c1';c.lineWidth=7;c.strokeRect(w*.22,50,w*.56,h-100);c.fillStyle='#243b53';c.fillRect(w*.19,y,w*.62,17);c.fillRect(w*.47,27,w*.06,y-27);c.strokeStyle='#c64f2b';c.lineWidth=5;c.beginPath();c.moveTo(w*.14,fall?y+25:y+85);c.lineTo(w*.14,fall?y+85:y+25);c.stroke();c.fillStyle='#c64f2b';c.beginPath();if(fall){c.moveTo(w*.14,y+95);c.lineTo(w*.11,y+77);c.lineTo(w*.17,y+77)}else{c.moveTo(w*.14,y+15);c.lineTo(w*.11,y+33);c.lineTo(w*.17,y+33)}c.fill();c.fillStyle='#c64f2b';c.font='700 15px system-ui';c.fillText(fall?'P ↓':'P ↑',w*.04,y+112);c.fillStyle='#6b46c1';c.fillText('Q = 0',w*.68,78);c.fillStyle='#17212b';c.font='700 16px system-ui';c.fillText('T changes',w*.37,h-25)}
  function graph(node,type,t){const{c,w,h}=canvas(node,152),pad={l:34,r:10,t:14,b:25},{p1,v1,v2}=state,minV=Math.min(v1,v2)*.86,maxV=Math.max(v1,v2)*1.12,x=v=>pad.l+(v-minV)/(maxV-minV)*(w-pad.l-pad.r),y=(z,min,max)=>h-pad.b-(z-min)/(max-min)*(h-pad.t-pad.b);c.strokeStyle='#9caeb5';c.beginPath();c.moveTo(pad.l,pad.t);c.lineTo(pad.l,h-pad.b);c.lineTo(w-pad.r,h-pad.b);c.stroke();c.fillStyle='#556270';c.font='10px system-ui';c.fillText(type==='pv'?'P':'T',8,16);c.fillText('V',w-12,h-7);const value=v=>type==='pv'?p1*(v1/v)**gamma:300*(v1/v)**(gamma-1),a=value(v1),b=value(v2),min=Math.min(a,b)*.86,max=Math.max(a,b)*1.14;c.strokeStyle=type==='pv'?'#6b46c1':'#c64f2b';c.lineWidth=2.5;c.beginPath();for(let i=0;i<=60;i++){const v=v1+(v2-v1)*i/60;i?c.lineTo(x(v),y(value(v),min,max)):c.moveTo(x(v),y(value(v),min,max))}c.stroke();const v=v1+(v2-v1)*t;c.fillStyle='#ef7d32';c.beginPath();c.arc(x(v),y(value(v),min,max),4,0,Math.PI*2);c.fill()}
  function render(){const t=Number(progress.value),v=state.v1+(state.v2-state.v1)*t,p=state.p1*(state.v1/v)**gamma;piston(t);graph($('pvCanvas'),'pv',t);graph($('tvCanvas'),'tv',t);$('liveState').textContent=`Now: V = ${f(v,5)} m³, P = ${f(p)} kPa`}
  function replay(){cancelAnimationFrame(animation);const start=performance.now(),duration=2300,step=now=>{progress.value=Math.min(1,(now-start)/duration);render();if(Number(progress.value)<1)animation=requestAnimationFrame(step)};progress.value=0;animation=requestAnimationFrame(step)}
  function load(){state=solveAdiabaticQuestion(q.value);if(state.error){message.textContent=state.error;message.classList.remove('hidden');lesson.classList.add('hidden');return}message.classList.add('hidden');lesson.classList.remove('hidden');$('answerValue').textContent=state.target==='pressure'?`P₂ = ${f(state.p2)} kPa`:state.target==='volume'?`V₂ = ${f(state.v2,5)} m³`:`W = ${f(state.workKJ)} kJ`;$('answerReason').textContent=state.target==='work'?'For an air-standard reversible adiabatic path, W = (P₂V₂ − P₁V₁)/(1 − γ).':'The air-standard adiabatic relation PVᵞ = constant connects the initial and final states.';$('initialState').textContent=`P₁ = ${f(state.p1)} kPa; V₁ = ${f(state.v1,5)} m³; Q = 0`;$('finalState').textContent=`P₂ = ${f(state.p2)} kPa; V₂ = ${f(state.v2,5)} m³; Q = 0`;progress.value=0;render();setTimeout(replay,350)}
  $('loadButton').addEventListener('click',load);$('sampleButton').addEventListener('click',()=>{q.value='Air initially occupies 0.04 m³ at 150 kPa. It expands adiabatically until its pressure becomes 60 kPa. Find V₂.';load()});$('replayButton').addEventListener('click',replay);progress.addEventListener('input',()=>{cancelAnimationFrame(animation);render()});addEventListener('resize',()=>{if(state)render()});const prompt=new URLSearchParams(location.search).get('prompt');if(prompt)q.value=prompt;load();
})(typeof window!=='undefined'?window:globalThis);
