const assert = require('assert');
const { solveIsothermalQuestion } = require('./isothermal-lab.js');
let result = solveIsothermalQuestion('An ideal gas initially occupies 0.04 meter cube at 150 kPa. It undergoes an isothermal expansion until its pressure becomes 60 kPa. Find V2.');
assert.strictEqual(result.target, 'volume');
assert.ok(Math.abs(result.v2 - 0.1) < 1e-9);
result = solveIsothermalQuestion('An ideal gas is compressed isothermally from 0.3 m3 to 0.2 m3. The initial pressure is 200 kPa. Find the final pressure.');
assert.strictEqual(result.target, 'pressure');
assert.strictEqual(result.p2, 300);
result = solveIsothermalQuestion('A gas at 100 kPa and 0.4 m3 expands isothermally to 0.8 m3. Find work done.');
assert.strictEqual(result.target, 'work');
assert.ok(Math.abs(result.workKJ - 27.7259) < 0.01);
console.log('isothermal lab tests passed');
